-- ============================================================
-- Phase 2A.12 - Seed practical material types for BOQ workshop use
-- ============================================================
-- Safe/idempotent data seed.
-- Does not modify existing materials, material_id, material_code, BOM, BOQ,
-- price snapshots, or LINE-related logic.

WITH type_seed(cat_code, code_prefix, name, description) AS (
  VALUES
    -- Steel and metal
    ('STL', 'BOX', 'Box tube', 'Square or rectangular steel tube'),
    ('STL', 'PIPE', 'Pipe', 'Round steel pipe'),
    ('STL', 'ROUND', 'Round bar', 'Round steel bar'),
    ('STL', 'FLAT', 'Flat bar', 'Flat steel bar'),
    ('STL', 'ANGLE', 'Angle', 'Steel angle'),
    ('STL', 'CHAN', 'Channel', 'Steel channel'),
    ('STL', 'PLATE', 'Plate', 'Steel plate'),
    ('STL', 'SHEET', 'Sheet', 'Metal sheet'),
    ('STL', 'ROD', 'Rod', 'Metal rod'),
    ('STL', 'REBAR', 'Rebar', 'Reinforcing steel bar'),
    ('STL', 'MESH', 'Mesh', 'Metal mesh'),
    ('STL', 'EXP', 'Expanded metal', 'Expanded metal sheet'),
    ('STL', 'PERF', 'Perforated sheet', 'Perforated metal sheet'),
    ('STL', 'SS', 'Stainless steel', 'Stainless steel material'),
    ('STL', 'ALU', 'Aluminum', 'Aluminum material'),
    ('STL', 'GALV', 'Galvanized steel', 'Galvanized steel material'),
    ('STL', 'WIRE', 'Metal wire', 'Metal wire material'),
    ('STL', 'HBEAM', 'H beam', 'H beam steel'),
    ('STL', 'IBEAM', 'I beam', 'I beam steel'),

    -- Wood and board
    ('WD', 'HMR', 'HMR board', 'Moisture resistant board'),
    ('WD', 'MDF', 'MDF board', 'Medium density fiberboard'),
    ('WD', 'PLY', 'Plywood', 'Plywood board'),
    ('WD', 'PB', 'Particle board', 'Particle board'),
    ('WD', 'OSB', 'OSB board', 'Oriented strand board'),
    ('WD', 'TIMBER', 'Timber', 'Timber or framing wood'),
    ('WD', 'SOLID', 'Solid wood', 'Solid wood material'),
    ('WD', 'VENEER', 'Wood veneer', 'Veneer sheet'),
    ('WD', 'BLOCK', 'Block board', 'Block board'),
    ('WD', 'LAMWD', 'Laminated wood', 'Laminated wood board'),
    ('WD', 'BATTEN', 'Wood batten', 'Wood batten or strip'),
    ('WD', 'FINGER', 'Finger joint wood', 'Finger joint wood'),
    ('WD', 'WPC', 'Wood plastic composite', 'WPC material'),
    ('WD', 'TEAK', 'Teak wood', 'Teak or decorative wood'),

    -- Paint and coating
    ('PNT', 'ACR', 'Acrylic paint', 'Acrylic paint'),
    ('PNT', 'OIL', 'Oil paint', 'Oil based paint'),
    ('PNT', 'SPR', 'Spray paint', 'Spray paint'),
    ('PNT', 'PRM', 'Primer', 'Primer paint'),
    ('PNT', 'THN', 'Thinner', 'Paint thinner or solvent'),
    ('PNT', 'PUT', 'Putty', 'Putty or filler'),
    ('PNT', 'TOP', 'Topcoat', 'Topcoat paint'),
    ('PNT', 'EPOXY', 'Epoxy coating', 'Epoxy paint or coating'),
    ('PNT', 'PU', 'PU coating', 'Polyurethane coating'),
    ('PNT', 'LACQ', 'Lacquer', 'Lacquer coating'),
    ('PNT', 'STAIN', 'Wood stain', 'Wood stain or dye'),
    ('PNT', 'SEAL', 'Sealer', 'Sealer coating'),
    ('PNT', 'COAT', 'Coating', 'General coating'),
    ('PNT', 'HARD', 'Hardener', 'Paint hardener'),
    ('PNT', 'TINT', 'Tint color', 'Tinting color'),
    ('PNT', 'SOLV', 'Solvent', 'Solvent material'),
    ('PNT', 'CLEAR', 'Clear coat', 'Clear coat or varnish'),

    -- Fabric and covering
    ('FAB', 'FABRIC', 'Fabric', 'General fabric'),
    ('FAB', 'CANVAS', 'Canvas', 'Canvas fabric'),
    ('FAB', 'VINYL', 'Vinyl covering', 'Vinyl sheet or covering'),
    ('FAB', 'TARP', 'Tarpaulin', 'Tarpaulin sheet'),
    ('FAB', 'CARPET', 'Carpet', 'Carpet or floor textile'),
    ('FAB', 'FELT', 'Felt', 'Felt fabric'),
    ('FAB', 'LEATHER', 'Leather', 'Leather or synthetic leather'),
    ('FAB', 'FOAM', 'Foam', 'Foam sheet or padding'),
    ('FAB', 'CURTAIN', 'Curtain fabric', 'Curtain fabric'),
    ('FAB', 'NET', 'Net fabric', 'Net or mesh fabric'),
    ('FAB', 'COVER', 'Covering', 'Covering material'),
    ('FAB', 'ELAST', 'Elastic', 'Elastic fabric or band'),
    ('FAB', 'ROPE', 'Rope', 'Rope or cord'),

    -- Hardware and fixtures
    ('HW', 'HINGE', 'Hinge', 'Door or furniture hinge'),
    ('HW', 'HANDLE', 'Handle', 'Handle or pull'),
    ('HW', 'SCREW', 'Screw', 'Screw'),
    ('HW', 'LOCK', 'Lock', 'Lock hardware'),
    ('HW', 'RUNNER', 'Runner', 'Drawer runner or slide'),
    ('HW', 'BRKT', 'Bracket', 'Bracket hardware'),
    ('HW', 'BOLT', 'Bolt', 'Bolt'),
    ('HW', 'NUT', 'Nut', 'Nut'),
    ('HW', 'WASHER', 'Washer', 'Washer'),
    ('HW', 'ANCHOR', 'Anchor', 'Wall anchor or expansion bolt'),
    ('HW', 'RIVET', 'Rivet', 'Rivet'),
    ('HW', 'NAIL', 'Nail', 'Nail'),
    ('HW', 'STAPLE', 'Staple', 'Staple'),
    ('HW', 'CLIP', 'Clip', 'Clip hardware'),
    ('HW', 'HOOK', 'Hook', 'Hook hardware'),
    ('HW', 'CHAIN', 'Chain', 'Chain hardware'),
    ('HW', 'CABLETIE', 'Cable tie', 'Cable tie'),
    ('HW', 'MAGNET', 'Magnet', 'Magnet hardware'),
    ('HW', 'CLAMP', 'Clamp', 'Clamp hardware'),
    ('HW', 'CASTER', 'Caster', 'Caster wheel'),
    ('HW', 'LEG', 'Leg', 'Furniture leg'),
    ('HW', 'RAIL', 'Rail', 'Rail or track hardware'),
    ('HW', 'KNOB', 'Knob', 'Knob hardware'),
    ('HW', 'MOUNT', 'Mount', 'Mounting hardware'),
    ('HW', 'TOOL', 'Tool', 'Hand tool'),
    ('HW', 'HAMMER', 'Hammer', 'Hammer or hammer head'),

    -- Plumbing
    ('PLB', 'PIPE', 'Pipe', 'Plumbing pipe'),
    ('PLB', 'FIT', 'Fitting', 'Pipe fitting'),
    ('PLB', 'ELBOW', 'Elbow', 'Pipe elbow'),
    ('PLB', 'TEE', 'Tee', 'Pipe tee'),
    ('PLB', 'VALVE', 'Valve', 'Valve'),
    ('PLB', 'DRAIN', 'Drain', 'Drainage part'),
    ('PLB', 'TRAP', 'Trap', 'Water trap'),
    ('PLB', 'HOSE', 'Hose', 'Hose'),
    ('PLB', 'PUMP', 'Pump', 'Water pump'),
    ('PLB', 'TANK', 'Tank', 'Water tank'),
    ('PLB', 'FAUCET', 'Faucet', 'Faucet or tap'),
    ('PLB', 'FLOOR', 'Floor drain', 'Floor drain'),
    ('PLB', 'PVC', 'PVC pipe', 'PVC plumbing material'),
    ('PLB', 'PPR', 'PPR pipe', 'PPR plumbing material'),
    ('PLB', 'HDPE', 'HDPE pipe', 'HDPE plumbing material'),
    ('PLB', 'CLAMP', 'Pipe clamp', 'Pipe clamp'),

    -- Glass and acrylic
    ('GLS', 'GLS', 'Glass', 'Glass sheet'),
    ('GLS', 'ACR', 'Acrylic sheet', 'Acrylic sheet'),
    ('GLS', 'MIR', 'Mirror', 'Mirror glass'),
    ('GLS', 'TEMP', 'Tempered glass', 'Tempered glass'),
    ('GLS', 'LAMGLS', 'Laminated glass', 'Laminated glass'),
    ('GLS', 'FROST', 'Frosted glass', 'Frosted glass'),
    ('GLS', 'TINT', 'Tinted glass', 'Tinted glass'),
    ('GLS', 'PC', 'Polycarbonate', 'Polycarbonate sheet'),
    ('GLS', 'PETG', 'PETG sheet', 'PETG plastic sheet'),
    ('GLS', 'PMMA', 'PMMA sheet', 'PMMA acrylic material'),
    ('GLS', 'FILM', 'Glass film', 'Glass film'),
    ('GLS', 'SEAL', 'Glass seal', 'Seal or gasket for glass'),

    -- Finishing materials
    ('FNR', 'HPL', 'High pressure laminate', 'HPL sheet'),
    ('FNR', 'EDG', 'Edge banding', 'Edge banding'),
    ('FNR', 'FILM', 'Film', 'Decorative film'),
    ('FNR', 'MEL', 'Melamine', 'Melamine finish'),
    ('FNR', 'WALL', 'Wall finish', 'Wall finish material'),
    ('FNR', 'PAINT', 'Paint finish', 'Paint used as finish material'),
    ('FNR', 'PRM', 'Primer finish', 'Primer used as finish material'),
    ('FNR', 'TOP', 'Topcoat finish', 'Topcoat used as finish material'),
    ('FNR', 'PUT', 'Putty finish', 'Putty or filler used as finish material'),
    ('FNR', 'THN', 'Thinner', 'Thinner or solvent'),
    ('FNR', 'VEN', 'Veneer finish', 'Veneer finish'),
    ('FNR', 'LAM', 'Laminate', 'Laminate finish'),
    ('FNR', 'PVC', 'PVC edge or sheet', 'PVC finishing material'),
    ('FNR', 'FOIL', 'Foil finish', 'Foil or decorative sheet'),
    ('FNR', 'WPAPER', 'Wallpaper', 'Wallpaper'),
    ('FNR', 'TILE', 'Tile', 'Tile finish'),
    ('FNR', 'STONE', 'Stone finish', 'Stone or stone-like finish'),

    -- Structure materials
    ('STR', 'HMR', 'HMR board', 'HMR used as structural/substrate board'),
    ('STR', 'MDF', 'MDF board', 'MDF used as structural/substrate board'),
    ('STR', 'PLY', 'Plywood', 'Plywood used as structural/substrate board'),
    ('STR', 'TIMBER', 'Timber', 'Timber structure'),
    ('STR', 'FRAME', 'Frame', 'Frame material'),
    ('STR', 'STUD', 'Stud', 'Stud or vertical framing'),
    ('STR', 'TRACK', 'Track', 'Track or horizontal framing'),
    ('STR', 'BOARD', 'Board', 'Board substrate'),
    ('STR', 'PANEL', 'Panel', 'Panel substrate'),
    ('STR', 'BOX', 'Box tube', 'Box tube for structure'),
    ('STR', 'PIPE', 'Pipe', 'Pipe for structure'),
    ('STR', 'ALU', 'Aluminum structure', 'Aluminum structural material'),
    ('STR', 'STEEL', 'Steel structure', 'Steel structural material'),

    -- Electrical and lighting
    ('ELC', 'SPOT', 'Spot light', 'Spot light'),
    ('ELC', 'STRIP', 'LED strip', 'LED strip'),
    ('ELC', 'PSU', 'Power supply', 'Power supply'),
    ('ELC', 'WIRE', 'Wire', 'Electrical wire'),
    ('ELC', 'PLUG', 'Plug', 'Electrical plug'),
    ('ELC', 'SW', 'Switch', 'Electrical switch'),
    ('ELC', 'LED', 'LED light', 'LED light'),
    ('ELC', 'TUBE', 'LED tube', 'LED tube light'),
    ('ELC', 'TRACK', 'Track light', 'Track light'),
    ('ELC', 'DOWN', 'Downlight', 'Downlight'),
    ('ELC', 'FLOOD', 'Flood light', 'Flood light'),
    ('ELC', 'PANEL', 'Panel light', 'Panel light'),
    ('ELC', 'DIMMER', 'Dimmer', 'Dimmer switch'),
    ('ELC', 'BREAKER', 'Breaker', 'Circuit breaker'),
    ('ELC', 'CONDUIT', 'Conduit', 'Electrical conduit'),
    ('ELC', 'JBOX', 'Junction box', 'Junction box'),
    ('ELC', 'CABLE', 'Cable', 'Electrical cable'),
    ('ELC', 'ADAPT', 'Adapter', 'Adapter'),
    ('ELC', 'SENSOR', 'Sensor', 'Electrical sensor'),
    ('ELC', 'CTRL', 'Controller', 'Lighting or electrical controller'),
    ('ELC', 'BAT', 'Battery', 'Battery'),
    ('ELC', 'LAMP', 'Lamp', 'Lamp'),
    ('ELC', 'SOCKET', 'Socket', 'Electrical socket'),

    -- Graphic and print materials
    ('GPM', 'VIN', 'Vinyl print', 'Vinyl print material'),
    ('GPM', 'STK', 'Sticker', 'Sticker material'),
    ('GPM', 'PP', 'PP print', 'PP print material'),
    ('GPM', 'PVC', 'PVC print', 'PVC print material'),
    ('GPM', 'BACKLIT', 'Backlit film', 'Backlit film'),
    ('GPM', 'CANVAS', 'Canvas print', 'Canvas print material'),
    ('GPM', 'FOAMBD', 'Foam board', 'Foam board print substrate'),
    ('GPM', 'SINTRA', 'Sintra board', 'Sintra board'),
    ('GPM', 'INK', 'Ink', 'Printing ink'),
    ('GPM', 'UV', 'UV print', 'UV printing material'),
    ('GPM', 'MESH', 'Mesh banner', 'Mesh print material'),
    ('GPM', 'BANNER', 'Banner', 'Banner material'),
    ('GPM', 'DECAL', 'Decal', 'Decal material'),
    ('GPM', 'POSTER', 'Poster', 'Poster print material'),
    ('GPM', 'BOARD', 'Print board', 'Print board substrate'),

    -- Hardware and fasteners
    ('HFN', 'HINGE', 'Hinge', 'Hinge hardware'),
    ('HFN', 'HANDLE', 'Handle', 'Handle hardware'),
    ('HFN', 'SCREW', 'Screw', 'Screw fastener'),
    ('HFN', 'LOCK', 'Lock', 'Lock hardware'),
    ('HFN', 'RUNNER', 'Runner', 'Runner or slide'),
    ('HFN', 'BRKT', 'Bracket', 'Bracket hardware'),
    ('HFN', 'BOLT', 'Bolt', 'Bolt fastener'),
    ('HFN', 'NUT', 'Nut', 'Nut fastener'),
    ('HFN', 'WASHER', 'Washer', 'Washer fastener'),
    ('HFN', 'ANCHOR', 'Anchor', 'Wall anchor or expansion bolt'),
    ('HFN', 'RIVET', 'Rivet', 'Rivet fastener'),
    ('HFN', 'NAIL', 'Nail', 'Nail fastener'),
    ('HFN', 'STAPLE', 'Staple', 'Staple fastener'),
    ('HFN', 'CLIP', 'Clip', 'Clip fastener'),
    ('HFN', 'HOOK', 'Hook', 'Hook fastener'),
    ('HFN', 'CLAMP', 'Clamp', 'Clamp fastener'),
    ('HFN', 'CABLETIE', 'Cable tie', 'Cable tie fastener'),

    -- Furniture and decor
    ('FDR', 'HINGE', 'Hinge', 'Furniture hinge'),
    ('FDR', 'HANDLE', 'Handle', 'Furniture handle'),
    ('FDR', 'SCREW', 'Screw', 'Furniture screw'),
    ('FDR', 'LOCK', 'Lock', 'Furniture lock'),
    ('FDR', 'RUNNER', 'Runner', 'Drawer runner'),
    ('FDR', 'BRKT', 'Bracket', 'Furniture bracket'),
    ('FDR', 'CABINET', 'Cabinet', 'Cabinet or cabinet part'),
    ('FDR', 'SHELF', 'Shelf', 'Shelf or shelving'),
    ('FDR', 'TABLE', 'Table', 'Table or table part'),
    ('FDR', 'CHAIR', 'Chair', 'Chair or seating part'),
    ('FDR', 'COUNTER', 'Counter', 'Counter furniture'),
    ('FDR', 'DISPLAY', 'Display fixture', 'Display fixture'),
    ('FDR', 'DECOR', 'Decor item', 'Decorative item'),
    ('FDR', 'LEG', 'Furniture leg', 'Furniture leg'),
    ('FDR', 'CASTER', 'Caster', 'Caster wheel'),
    ('FDR', 'RAIL', 'Rail', 'Furniture rail'),
    ('FDR', 'KNOB', 'Knob', 'Furniture knob'),
    ('FDR', 'PANEL', 'Panel', 'Decorative panel'),
    ('FDR', 'MIRROR', 'Mirror', 'Decor mirror'),

    -- Multimedia and equipment
    ('MEM', 'TV', 'TV', 'Television display'),
    ('MEM', 'MONITOR', 'Monitor', 'Monitor display'),
    ('MEM', 'PLAYER', 'Player', 'Media player'),
    ('MEM', 'SPEAK', 'Speaker', 'Speaker'),
    ('MEM', 'AMP', 'Amplifier', 'Audio amplifier'),
    ('MEM', 'MIC', 'Microphone', 'Microphone'),
    ('MEM', 'CAM', 'Camera', 'Camera'),
    ('MEM', 'PROJ', 'Projector', 'Projector'),
    ('MEM', 'SENSOR', 'Sensor', 'Sensor equipment'),
    ('MEM', 'ROUTER', 'Router', 'Network router'),
    ('MEM', 'CABLE', 'Signal cable', 'Signal cable'),
    ('MEM', 'REMOTE', 'Remote', 'Remote controller'),
    ('MEM', 'CTRL', 'Controller', 'Control equipment'),
    ('MEM', 'STAND', 'Stand', 'Equipment stand'),
    ('MEM', 'BRKT', 'Bracket', 'Equipment bracket'),
    ('MEM', 'MOUNT', 'Mount', 'Equipment mount'),
    ('MEM', 'MEDIA', 'Media equipment', 'General media equipment'),

    -- Installation and logistics
    ('INS', 'LABOR', 'Labor', 'Installation labor'),
    ('INS', 'TRANS', 'Transport', 'Transport or delivery'),
    ('INS', 'RENT', 'Rental', 'Tool or equipment rental'),
    ('INS', 'TRAVEL', 'Travel', 'Travel cost'),
    ('INS', 'LIFT', 'Lifting', 'Lifting or crane work'),
    ('INS', 'PACK', 'Packing', 'Packing material or service'),
    ('INS', 'INSTALL', 'Install', 'Installation work'),
    ('INS', 'REMOVE', 'Remove', 'Removal or dismantling work'),
    ('INS', 'CLEAN', 'Cleaning', 'Cleaning work'),
    ('INS', 'PROTECT', 'Protection', 'Site protection'),
    ('INS', 'PERMIT', 'Permit', 'Permit or site fee'),
    ('INS', 'TOOL', 'Tool', 'Installation tool'),

    -- Consumables
    ('COM', 'BRUSH', 'Brush', 'Paint or cleaning brush'),
    ('COM', 'ROLLER', 'Roller', 'Paint roller'),
    ('COM', 'CLOTH', 'Cloth', 'Cleaning or scrap cloth'),
    ('COM', 'RAG', 'Rag', 'Scrap cloth or rag'),
    ('COM', 'WELD', 'Welding rod', 'Welding rod or welding consumable'),
    ('COM', 'NAIL', 'Nail', 'Nail consumable'),
    ('COM', 'STAPLE', 'Staple', 'Staple or pin nail'),
    ('COM', 'SAND', 'Sandpaper', 'Sandpaper'),
    ('COM', 'DISC', 'Disc', 'Grinding or cutting disc'),
    ('COM', 'BLADE', 'Blade', 'Saw blade or cutter blade'),
    ('COM', 'DRILL', 'Drill bit', 'Drill bit'),
    ('COM', 'BROOM', 'Broom', 'Broom or cleaning tool'),
    ('COM', 'TRASH', 'Trash bag', 'Trash bag'),
    ('COM', 'GLOVE', 'Glove', 'Work glove'),
    ('COM', 'MASK', 'Mask', 'Safety or dust mask'),
    ('COM', 'TAPE', 'Consumable tape', 'Consumable tape'),
    ('COM', 'CUTTER', 'Cutter', 'Cutter or knife'),
    ('COM', 'BAG', 'Bag', 'Bag or sack'),

    -- Custom fabrication
    ('CFN', 'CNC', 'CNC work', 'CNC cutting or routing'),
    ('CFN', 'LASER', 'Laser work', 'Laser cutting or engraving'),
    ('CFN', 'WELD', 'Welding work', 'Welding fabrication'),
    ('CFN', 'BEND', 'Bending work', 'Bending fabrication'),
    ('CFN', 'CUT', 'Cutting work', 'Custom cutting'),
    ('CFN', 'FRAME', 'Frame fabrication', 'Custom frame fabrication'),
    ('CFN', 'PANEL', 'Panel fabrication', 'Custom panel fabrication'),
    ('CFN', 'ASSEMB', 'Assembly', 'Assembly work'),
    ('CFN', 'FINISH', 'Finishing work', 'Custom finishing work'),
    ('CFN', 'REWORK', 'Rework', 'Rework or modification'),
    ('CFN', 'CUSTOM', 'Custom work', 'General custom fabrication'),
    ('CFN', 'MOCKUP', 'Mockup', 'Mockup fabrication'),

    -- Adhesive, tape, sealant
    ('ADH', 'GLUE', 'Glue', 'General glue'),
    ('ADH', 'SIL', 'Silicone', 'Silicone sealant'),
    ('ADH', 'TAPE', 'Tape', 'General tape'),
    ('ADH', 'EPOXY', 'Epoxy adhesive', 'Epoxy adhesive'),
    ('ADH', 'CONTACT', 'Contact adhesive', 'Contact adhesive'),
    ('ADH', 'PU', 'PU adhesive', 'Polyurethane adhesive'),
    ('ADH', 'ACRY', 'Acrylic adhesive', 'Acrylic adhesive'),
    ('ADH', 'SEAL', 'Sealant', 'Sealant'),
    ('ADH', 'FOAM', 'Foam tape', 'Foam tape or foam adhesive'),
    ('ADH', 'VELCRO', 'Velcro tape', 'Hook and loop tape'),
    ('ADH', 'DBTAPE', 'Double-sided tape', 'Double-sided tape'),
    ('ADH', 'MASK', 'Masking tape', 'Masking tape'),
    ('ADH', 'HOTMELT', 'Hot melt glue', 'Hot melt glue'),

    -- Miscellaneous
    ('MISC', 'GEN', 'General', 'General miscellaneous material'),
    ('MISC', 'OTHER', 'Other', 'Other material'),
    ('MISC', 'SAMPLE', 'Sample', 'Sample material'),
    ('MISC', 'SPARE', 'Spare part', 'Spare part'),
    ('MISC', 'UNKNOWN', 'Unknown', 'Unknown material type'),
    ('MISC', 'SERVICE', 'Service', 'Service or non-material item'),
    ('MISC', 'CUSTOM', 'Custom', 'Custom miscellaneous item')
)
INSERT INTO public.material_types (category_id, name, code_prefix, description, is_active)
SELECT
  category.id,
  type_seed.name,
  type_seed.code_prefix,
  type_seed.description,
  true
FROM type_seed
JOIN public.mat_category AS category
  ON category.cat_code = type_seed.cat_code
WHERE category.is_active IS TRUE
ON CONFLICT (category_id, code_prefix) DO NOTHING;
