-- ============================================================
-- Phase 2A.12 - Thai labels for material types
-- ============================================================
-- Display material type names as "Thai / English" without changing prefixes,
-- ids, existing material references, material codes, BOM, BOQ, or snapshots.
-- Safe to rerun.

WITH thai_labels(english_name, thai_name) AS (
  VALUES
    ('Acrylic adhesive', 'กาวอะคริลิค'),
    ('Acrylic paint', 'สีอะคริลิค'),
    ('Acrylic sheet', 'แผ่นอะคริลิค'),
    ('Adapter', 'อะแดปเตอร์'),
    ('Aluminum', 'อะลูมิเนียม'),
    ('Aluminum structure', 'โครงอะลูมิเนียม'),
    ('Amplifier', 'แอมป์ขยายเสียง'),
    ('Anchor', 'พุก / แองเคอร์'),
    ('Angle', 'เหล็กฉาก'),
    ('Assembly', 'งานประกอบ'),
    ('Backlit film', 'ฟิล์มแบ็คลิท'),
    ('Bag', 'ถุง'),
    ('Banner', 'แบนเนอร์'),
    ('Battery', 'แบตเตอรี่'),
    ('Bending work', 'งานพับ / ดัด'),
    ('Blade', 'ใบมีด / ใบตัด'),
    ('Block board', 'บล็อกบอร์ด'),
    ('Board', 'บอร์ด / แผ่น'),
    ('Bolt', 'โบลท์'),
    ('Box tube', 'เหล็กกล่อง'),
    ('Breaker', 'เบรกเกอร์'),
    ('Bracket', 'ฉากรับ / ขายึด'),
    ('Broom', 'ไม้กวาด'),
    ('Brush', 'แปรง'),
    ('Cabinet', 'ตู้'),
    ('Cable', 'สายไฟ / สายเคเบิล'),
    ('Cable tie', 'เคเบิลไทร์'),
    ('Camera', 'กล้อง'),
    ('Canvas', 'ผ้าแคนวาส'),
    ('Canvas print', 'งานพิมพ์ผ้าแคนวาส'),
    ('Carpet', 'พรม'),
    ('Caster', 'ล้อเลื่อน'),
    ('Chain', 'โซ่'),
    ('Chair', 'เก้าอี้'),
    ('Channel', 'เหล็กราง'),
    ('Clamp', 'แคลมป์ / ตัวจับ'),
    ('Cleaning', 'งานทำความสะอาด'),
    ('Clear coat', 'เคลียร์โค้ท'),
    ('Clip', 'คลิป / ตัวหนีบ'),
    ('Cloth', 'ผ้า'),
    ('CNC work', 'งาน CNC'),
    ('Coating', 'สารเคลือบ'),
    ('Conduit', 'ท่อร้อยสายไฟ'),
    ('Contact adhesive', 'กาวยาง'),
    ('Consumable tape', 'เทปสิ้นเปลือง'),
    ('Controller', 'คอนโทรลเลอร์'),
    ('Counter', 'เคาน์เตอร์'),
    ('Covering', 'วัสดุคลุม'),
    ('Curtain fabric', 'ผ้าม่าน'),
    ('Custom', 'แบบกำหนดเอง'),
    ('Custom work', 'งานสั่งทำ'),
    ('Cutter', 'คัตเตอร์'),
    ('Cutting work', 'งานตัด'),
    ('Decal', 'ดีคอล'),
    ('Decor item', 'ของตกแต่ง'),
    ('Dimmer', 'ดิมเมอร์'),
    ('Disc', 'ใบเจียร / ใบตัด'),
    ('Display fixture', 'อุปกรณ์ดิสเพลย์'),
    ('Double-sided tape', 'เทปสองหน้า'),
    ('Downlight', 'ดาวน์ไลท์'),
    ('Drain', 'ท่อระบายน้ำ'),
    ('Drill bit', 'ดอกสว่าน'),
    ('Edge banding', 'เส้นปิดขอบ'),
    ('Elastic', 'ยางยืด'),
    ('Elbow', 'ข้องอ'),
    ('Epoxy adhesive', 'กาวอีพ็อกซี่'),
    ('Epoxy coating', 'สี / เคลือบอีพ็อกซี่'),
    ('Expanded metal', 'เหล็กฉีก'),
    ('Fabric', 'ผ้า'),
    ('Faucet', 'ก๊อกน้ำ'),
    ('Felt', 'ผ้าสักหลาด'),
    ('Film', 'ฟิล์ม'),
    ('Finger joint wood', 'ไม้ประสาน'),
    ('Finishing work', 'งานเก็บผิว'),
    ('Fitting', 'ข้อต่อ'),
    ('Flat bar', 'เหล็กแบน'),
    ('Flood light', 'โคมฟลัดไลท์'),
    ('Floor drain', 'ตะแกรงระบายน้ำพื้น'),
    ('Foam', 'โฟม'),
    ('Foam board', 'โฟมบอร์ด'),
    ('Foam tape', 'เทปโฟม'),
    ('Foil finish', 'ฟอยล์ตกแต่ง'),
    ('Frame', 'โครงเฟรม'),
    ('Frame fabrication', 'งานผลิตโครงเฟรม'),
    ('Frosted glass', 'กระจกฝ้า'),
    ('Furniture leg', 'ขาเฟอร์นิเจอร์'),
    ('Galvanized steel', 'เหล็กชุบสังกะสี'),
    ('General', 'ทั่วไป'),
    ('Glass', 'กระจก'),
    ('Glass film', 'ฟิล์มกระจก'),
    ('Glass seal', 'ซีลกระจก'),
    ('Glove', 'ถุงมือ'),
    ('Glue', 'กาว'),
    ('H beam', 'เหล็กเอชบีม'),
    ('HDPE pipe', 'ท่อ HDPE'),
    ('HMR board', 'ไม้ HMR'),
    ('Hammer', 'ค้อน'),
    ('Handle', 'มือจับ'),
    ('Hardener', 'ฮาร์ดเดนเนอร์'),
    ('High pressure laminate', 'ลามิเนต HPL'),
    ('Hinge', 'บานพับ'),
    ('Hook', 'ตะขอ'),
    ('Hose', 'สายยาง'),
    ('Hot melt glue', 'กาวร้อน'),
    ('I beam', 'เหล็กไอบีม'),
    ('Ink', 'หมึกพิมพ์'),
    ('Install', 'งานติดตั้ง'),
    ('Junction box', 'กล่องพักสาย'),
    ('Knob', 'ปุ่มจับ'),
    ('LED light', 'ไฟ LED'),
    ('LED strip', 'ไฟเส้น LED'),
    ('LED tube', 'หลอด LED'),
    ('Labor', 'ค่าแรง'),
    ('Lacquer', 'แลคเกอร์'),
    ('Laminate', 'ลามิเนต'),
    ('Laminated glass', 'กระจกลามิเนต'),
    ('Laminated wood', 'ไม้ลามิเนต'),
    ('Lamp', 'หลอดไฟ / โคมไฟ'),
    ('Laser work', 'งานเลเซอร์'),
    ('Leather', 'หนัง / หนังเทียม'),
    ('Leg', 'ขา'),
    ('Lifting', 'งานยก'),
    ('Lock', 'กุญแจ / ตัวล็อก'),
    ('MDF board', 'ไม้ MDF'),
    ('Magnet', 'แม่เหล็ก'),
    ('Mask', 'หน้ากาก'),
    ('Masking tape', 'เทปกาวกระดาษ'),
    ('Media equipment', 'อุปกรณ์มัลติมีเดีย'),
    ('Melamine', 'เมลามีน'),
    ('Mesh', 'ตะแกรง / เมช'),
    ('Mesh banner', 'แบนเนอร์เมช'),
    ('Metal wire', 'ลวดโลหะ'),
    ('Microphone', 'ไมโครโฟน'),
    ('Mirror', 'กระจกเงา'),
    ('Mockup', 'ม็อกอัพ'),
    ('Monitor', 'จอมอนิเตอร์'),
    ('Mount', 'ขายึด'),
    ('Nail', 'ตะปู'),
    ('Net fabric', 'ผ้าตาข่าย'),
    ('Nut', 'น็อตตัวเมีย'),
    ('OSB board', 'ไม้ OSB'),
    ('Oil paint', 'สีน้ำมัน'),
    ('Other', 'อื่น ๆ'),
    ('PP print', 'งานพิมพ์ PP'),
    ('PVC edge or sheet', 'PVC ปิดขอบ / แผ่น PVC'),
    ('PVC pipe', 'ท่อ PVC'),
    ('PVC print', 'งานพิมพ์ PVC'),
    ('PU adhesive', 'กาว PU'),
    ('PU coating', 'เคลือบ PU'),
    ('Packing', 'งานแพ็ก / บรรจุ'),
    ('Paint finish', 'สีงานผิว'),
    ('Panel', 'แผง'),
    ('Panel fabrication', 'งานผลิตแผง'),
    ('Panel light', 'ไฟพาเนล'),
    ('Particle board', 'ไม้ปาร์ติเกิล'),
    ('Perforated sheet', 'แผ่นเจาะรู'),
    ('Permit', 'ค่าอนุญาต / ค่าพื้นที่'),
    ('PETG sheet', 'แผ่น PETG'),
    ('Pipe', 'ท่อ'),
    ('Pipe clamp', 'แคลมป์รัดท่อ'),
    ('Plate', 'แผ่นเพลท'),
    ('Player', 'เครื่องเล่นสื่อ'),
    ('Plug', 'ปลั๊ก'),
    ('Plywood', 'ไม้อัด'),
    ('PMMA sheet', 'แผ่น PMMA'),
    ('Polycarbonate', 'โพลีคาร์บอเนต'),
    ('Poster', 'โปสเตอร์'),
    ('Power supply', 'เพาเวอร์ซัพพลาย'),
    ('PPR pipe', 'ท่อ PPR'),
    ('Primer', 'สีรองพื้น'),
    ('Primer finish', 'รองพื้นงานผิว'),
    ('Print board', 'บอร์ดงานพิมพ์'),
    ('Projector', 'โปรเจคเตอร์'),
    ('Protection', 'วัสดุป้องกันหน้างาน'),
    ('Pump', 'ปั๊มน้ำ'),
    ('Putty', 'โป๊ว'),
    ('Putty finish', 'โป๊วเก็บผิว'),
    ('Rag', 'เศษผ้า'),
    ('Rail', 'ราง'),
    ('Rebar', 'เหล็กเส้น'),
    ('Remote', 'รีโมท'),
    ('Remove', 'งานรื้อถอน'),
    ('Rental', 'ค่าเช่า'),
    ('Rework', 'งานแก้ไข'),
    ('Rivet', 'รีเวท'),
    ('Rod', 'เหล็กเส้นกลม'),
    ('Roller', 'ลูกกลิ้ง'),
    ('Rope', 'เชือก'),
    ('Round bar', 'เหล็กกลม'),
    ('Router', 'เราเตอร์'),
    ('Runner', 'รางลิ้นชัก'),
    ('Sample', 'ตัวอย่าง'),
    ('Sandpaper', 'กระดาษทราย'),
    ('Screw', 'สกรู'),
    ('Sealant', 'ซีลแลนท์'),
    ('Sealer', 'ซีลเลอร์'),
    ('Sensor', 'เซนเซอร์'),
    ('Service', 'งานบริการ'),
    ('Sheet', 'แผ่น'),
    ('Shelf', 'ชั้นวาง'),
    ('Signal cable', 'สายสัญญาณ'),
    ('Silicone', 'ซิลิโคน'),
    ('Sintra board', 'ซินทราบอร์ด'),
    ('Socket', 'เต้ารับ'),
    ('Solid wood', 'ไม้จริง'),
    ('Solvent', 'ตัวทำละลาย'),
    ('Spare part', 'อะไหล่'),
    ('Speaker', 'ลำโพง'),
    ('Spot light', 'สปอตไลท์'),
    ('Spray paint', 'สีสเปรย์'),
    ('Stainless steel', 'สแตนเลส'),
    ('Stand', 'ขาตั้ง'),
    ('Staple', 'ลูกแม็ก / ลวดเย็บ'),
    ('Steel structure', 'โครงสร้างเหล็ก'),
    ('Sticker', 'สติกเกอร์'),
    ('Stone finish', 'วัสดุผิวหิน'),
    ('Stud', 'สตัด / โครงตั้ง'),
    ('Switch', 'สวิตช์'),
    ('TV', 'ทีวี'),
    ('Table', 'โต๊ะ'),
    ('Tank', 'ถังน้ำ'),
    ('Tape', 'เทป'),
    ('Tarpaulin', 'ผ้าใบ'),
    ('Teak wood', 'ไม้สัก'),
    ('Tee', 'สามทาง'),
    ('Tempered glass', 'กระจกเทมเปอร์'),
    ('Thinner', 'ทินเนอร์'),
    ('Tile', 'กระเบื้อง'),
    ('Timber', 'ไม้โครง'),
    ('Tint color', 'แม่สี / สีผสม'),
    ('Tinted glass', 'กระจกสีชา / กระจกตัดแสง'),
    ('Tool', 'เครื่องมือ'),
    ('Topcoat', 'สีทับหน้า'),
    ('Topcoat finish', 'สีทับหน้างานผิว'),
    ('Track', 'ราง'),
    ('Track light', 'ไฟแทร็ก'),
    ('Transport', 'ค่าขนส่ง'),
    ('Trap', 'ท่อน้ำทิ้ง / P-trap'),
    ('Trash bag', 'ถุงขยะ'),
    ('Travel', 'ค่าเดินทาง'),
    ('Unknown', 'ไม่ระบุ'),
    ('UV print', 'งานพิมพ์ UV'),
    ('Valve', 'วาล์ว'),
    ('Velcro tape', 'เทปตีนตุ๊กแก'),
    ('Veneer finish', 'วีเนียร์งานผิว'),
    ('Vinyl covering', 'ไวนิลคลุม / ปิดผิว'),
    ('Vinyl print', 'งานพิมพ์ไวนิล'),
    ('Wall finish', 'วัสดุผนัง'),
    ('Washer', 'แหวนรอง'),
    ('Welding rod', 'ลวดเชื่อม'),
    ('Welding work', 'งานเชื่อม'),
    ('Wire', 'สายไฟ'),
    ('Wood batten', 'ไม้ระแนง'),
    ('Wood plastic composite', 'ไม้พลาสติก WPC'),
    ('Wood stain', 'สีย้อมไม้'),
    ('Wood veneer', 'วีเนียร์ไม้'),
    ('Wallpaper', 'วอลเปเปอร์')
),
current_names AS (
  SELECT
    material_types.id,
    CASE
      WHEN material_types.name LIKE '% / %'
        THEN regexp_replace(material_types.name, '^.* / ', '')
      ELSE material_types.name
    END AS english_name
  FROM public.material_types
)
UPDATE public.material_types AS material_types
SET
  name = thai_labels.thai_name || ' / ' || current_names.english_name,
  updated_at = now()
FROM current_names
JOIN thai_labels
  ON thai_labels.english_name = current_names.english_name
WHERE material_types.id = current_names.id
  AND material_types.name IS DISTINCT FROM thai_labels.thai_name || ' / ' || current_names.english_name;
